export const ARTICLES_RECIEVE = 'ARTICLES_RECIEVE';
export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_REQUEST_SUCCESS = 'ARTICLES_REQUEST_SUCCESS';
export const ARTICLES_REQUEST_FAILURE = 'ARTICLES_REQUEST_FAILURE';

export const SETTINGS_SAVE = 'SETTINGS_SAVE';
